version: "3.8"

services:
  # Tu aplicación Next.js
  vizapp:
    build: .
    container_name: vizapp-app
    ports:
      - "3000:3000"
    environment:
      BETTER_AUTH_SECRET: "6gfFbDhGztTai9hQdyx5Ucy2qeGmbLC8"
      BETTER_AUTH_URL: "http://tu-dominio.com"
      NEXT_PUBLIC_API_URL: "http://tu-dominio.com"
      DATABASE_URL: "postgresql://admin:sagata79@postgres:5432/vizapp?schema=public"
      AWS_ENDPOINT_URL_S3: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      AWS_REGION: "us-east-1"
      S3_BUCKET_NAME: "vizapp"
      SMTP_HOST: "mail.laas.fr"
      SMTP_PORT: "587"
      SMTP_USER: "pnudel"
      SMTP_PASSWORD: "Lz7mFwpTnt9L"
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: vizapp-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sagata79
      POSTGRES_DB: vizapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # MinIO para almacenamiento S3
  minio:
    image: minio/minio:latest
    container_name: vizapp-minio
    ports:
      - "9000:9000" # API S3 (uso interno)
      - "9001:9001" # Console web (acceso externo)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /files:/data # Donde se guardan los archivos
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
