/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Update Job': ApiRouteHandler<{ userId: string; jobId: string; name: string; description?: string }, unknown, never>
    'Delete Job Files': ApiRouteHandler<{ userId: string; userName: string; userPassword: string; fileName: string; folderId: string; fileType: 'sourceFiles' | 'datasetsFiles' | 'reqFile' }, unknown, never>
    'Create Job': ApiRouteHandler<{ userId: string; userName: string; userPassword: string; name: string; description?: string }, unknown, never>
  }
    
}