/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CheckInputFiles': ApiRouteHandler<{ userId: string; simId: string }, unknown, never>
    'UploadInputFiles': ApiRouteHandler<{ userId: string; simId: string; files: Array<{ filename: string; contentType: string; data: string }> }, unknown, never>
  }
    
}